#!/bin/bash

function show_usage {
    echo "Usage: emacs-nw [-h] [-H] [EMACSCLIENT-OPTIONS]"
    echo "Start a terminal Emacs session to a running Emacs instance."
    echo ""
    echo "If no Emacs instance is running, this command starts one."
    echo ""
    echo "    -h, --help  show this help list"
    echo "    -H          show the help of the underlying emacsclient command"
    echo ""
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    show_usage
    exit 0
elif [ "$1" == "-H" ]; then
    emacsclient --help
    exit 0
fi

# If the terminal version of Emacs looks off color-wise, set the TERM variable
# so Emacs knows it can use 256 colors. A brute force approach would be to
# precede the following command with
#
#     env TERM=xterm-256color

# -nw    open a new Emacs frame on the current terminal
# -a ""  start new Emacs instance if none is running
# $@     expand all positional parameters to separate words

emacsclient -nw -a "" "$@"
