#!/bin/bash

function show_usage {
    echo "Usage: magit [OPTION]"
    echo "Start a terminal Emacs session with magit for the Git repo in the current directory"
    echo ""
    echo "  -h, --help  give this help list"
}

if [ "$1" == "" ]; then
    git status > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        working_dir=$(pwd)
        env TERM=xterm-256color emacsclient -nw -a "" --eval "(magit-status-internal \"${working_dir}/.\")"
    else
        echo "The current directory is not a Git repo"
        exit 1
    fi
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    show_usage
    exit 0
else
    show_usage
    exit 1
fi
