This repo contains my personal configuration of the [[http://spacemacs.org/][Spacemacs]] distribution of
Emacs.

* Installation

This configuration comes with two shell scripts:

- emacs-nw :: starts the terminal version of Spacemacs
- magit :: starts magit using the terminal version of Spacemasc

Copy these scripts to a directory in your path, for example ~/.local/bin~.

* User configuration

You can find the user configuration in ~user-config.el~

* Custom scripts

The second script starts Emacs and starts magit for the current directory:
#+BEGIN_SRC sh :noweb tangle :tangle magit :tangle-mode (identity #o764)
#!/bin/bash

function show_usage {
    echo "Usage: magit [OPTION]"
    echo "Start a terminal Emacs session with magit for the Git repo in the current directory"
    echo ""
    echo "  -h, --help  give this help list"
}

if [ "$1" == "" ]; then
    git status > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        working_dir=$(pwd)
        env TERM=xterm-256color emacsclient -nw -a "" --eval "(magit-status-internal \"${working_dir}/.\")"
    else
        echo "The current directory is not a Git repo"
        exit 1
    fi
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    show_usage
    exit 0
else
    show_usage
    exit 1
fi
#+END_SRC

Initially I called =magit-status= when the current directory was not a Git repo.
This would start Helm so the user could select a Git directory. Unfortunately it
turned out that when the user would aborted this selection, e.g. by =C-g=, and
close the client, the display of characters in the terminal was corrupted.
