- [ ] add new option to ~emacs-nw~ script to *not* start Emacs daemon
- [ ] support dash using compleseus
- [ ] allow machine-dependent excluded packages
- [ ] allow machine-dependent additional packages
- [ ] allow machine-dependent font size

* [2025-01-02 Thu]

- [X] fix icon for LSP actions on modeline

The icon for the LSP actions, a light bulb, wasn't shown on the modeline. It
turns out an icons was used from the octicon font set, which wasn't installed
locally. I installed that font set using command ~all-the-icons-install-fonts~,
which is provided by package [[https://github.com/domtronn/all-the-icons.el][all-the-icons]]. This command also installed some
other font sets.

FYI, all-the-icons is a dependency of package [[https://github.com/TheBB/spaceline][spaceline]], which Spacemacs uses
for the modeline.

However... I'm don't know what the value of the light bulb is. My Spacemacs
installation shows the number of code actions available (at point), which is
nice, but the light bulb itself is always "switched off". Looking at the code in
~lsp-modeline.el~, it's never "turned on". So the only thing that changes in the
code action segment is the number of actions. Because I don't like the visuals
of the light bulb, I removed it.

Remarks:

1. By default there are 2 code actions, one to "fix all" and one to
   organize the imports. As mentioned, the number of code actions changes when
   point is on an actionable item, such as an unused variable.
2. The code action segment can also show the description of the preferred code
   actions. This adds a whole sentence to the modeline, which changes when you
   move point, and makes for a "restless" UX.


- [X] remove workaround for [[https://github.com/syl20bnr/spacemacs/issues/16276][spacemacs#16276]], "Keyboard + Command hints stop showing"

* [2024-12-30 Mon]

- [X] remove warning about orphan packages

On Spacemacs startup, Spacemacs mentioned it would delete 2 orphan packages,
~guile~ and ~mu4e~. These are system packages that come with Guix packages and
the deletion would (silently) fail. Spacemacs would try again the next time it
started. I've added both packages to ~dotspacemacs-additional-packages~ so
Spacemacs leaves them alone.


- [X] update config for latest Emacs version on Guix

I updated spacemacs to commit abba23b6 from 25 December 2024 and used Emacs 29.4
for that.

* [2024-05-17 Fri]

- [X] move custom settings to machine local file

* [2024-03-23 Sat]

- [ ] make ~main~ the default branch

It turned out this was already the default branch.

- [X] merge ~develop~ branch to ~main~
- [X] describe file to load local changes
- [X] describe update of Git submodule snippets

* [2024-03-04 Mon]

- [X] describe installation in README.org

* [2024-03-02 Sat]

- [X] remove ~magit~ shell script

I have never used this script "in production". I only used it to test it and
even then it was prone to corrupting the display of characters in the terminal.
